# Generated by Django 4.1.3 on 2022-12-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loged',
            field=models.BooleanField(default=False),
        ),
    ]
