# Generated by Django 4.1.3 on 2022-12-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
