# Generated by Django 4.1.3 on 2022-12-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_rename_username_user_username_user_tg_usname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_usname',
        ),
    ]
