# Generated by Django 4.1.7 on 2023-03-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_telegramuser_delete_user_remove_product_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
