# Generated by Django 4.1.7 on 2023-03-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_telegramuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='game',
        ),
    ]
