# Generated by Django 4.1.7 on 2023-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_rename_info_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
