# Generated by Django 4.1.7 on 2023-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_product_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
