# Generated by Django 4.1.7 on 2023-03-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_rename_product_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='username',
        ),
    ]
