# Generated by Django 4.1.7 on 2023-03-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_remove_telegramuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
    ]
