# Generated by Django 4.1.7 on 2023-04-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_alter_account_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='$', max_length=2),
            preserve_default=False,
        ),
    ]
